### ISSUE TITLE
Your project does not compile

### ISSUE THREAD

**Issue by s0hel** [vijjayy81/spring-boot-jpa-rest-demo-filter-paging-sorting#1]
You are missing artifacts

**Comment by vijjayy81** [comment]
The project is building without issues with maven and JDK8. Also the application is running with 'mvn spring-boot:run'. Closing the issue.

**Comment by Zoheb-hassan** [comment]
These do not resolve in EmployeesDAO
```import org.vijjayy.demo.springframework.boot.jpa.v1.api.model.ApiModelEmployeeResource;
import org.vijjayy.demo.springframework.boot.jpa.v1.api.model.ApiModelEmployees;
import org.vijjayy.demo.springframework.boot.jpa.v1.api.model.ApiModelPageAndSort;```

**Comment by vijjayy81** [comment]
Those are the model classes from swagger spec, will be generated automatically by this plugin  from the pom.

			<plugin>
				<groupId>io.swagger</groupId>
				<artifactId>swagger-codegen-maven-plugin</artifactId>
				<version>2.3.1</version>
				<executions>
					<execution>
						<phase>generate-sources</phase>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<inputSpec>src/main/resources/swagger.yaml</inputSpec>
							<language>spring</language>
							<output>${project.build.directory}/generated-sources</output>
							<apiPackage>org.vijjayy.demo.springframework.boot.jpa.v1.api</apiPackage>
							<modelPackage>org.vijjayy.demo.springframework.boot.jpa.v1.api.model</modelPackage>
							<invokerPackage>aorg.vijjayy.demo.springframework.boot.jpa.v1.api.invoker</invokerPackage>
							<generateSupportingFiles>false</generateSupportingFiles>
							<modelNamePrefix>ApiModel</modelNamePrefix>
							<configOptions>
								<sourceFolder>swagger</sourceFolder>
								<interfaceOnly>true</interfaceOnly>
								<generateModelTests>true</generateModelTests>
								<dateLibrary>java8</dateLibrary>
								<useTags>true</useTags>
								<serializableModel>true</serializableModel>
							</configOptions>
						</configuration>
					</execution>
				</executions>
			</plugin>

The generated files are part of the 'target/generated-sources/swagger'.

In your IDE workplace you may have to manually set the classpath if not done by automatically(Most of the latest Eclipse does this automatically).
