### ISSUE TITLE
Collections

### ISSUE THREAD

**Issue by raghu502** [vijjayy81/spring-boot-jpa-rest-demo-filter-paging-sorting#3]
How to search in case of relations, i mean one to many.

**Comment by zenonflo** [comment]
One to many is easy, manytomany needs lots of tailoring in the code. 
not sure if @vijjayy81 can take a look and add an example

**Comment by zenonasz** [comment]
one to many is easy, not much changes needed, as long as you set the relation in the model and search by id. 
Many to many is an issue, need lots of tailoring to the code, @vijjayy81 might have a solution for this.

**Comment by vijjayy81** [comment]
This is simple demonstration for exposing table as service in a controlled manner. I have not thought about complex Many to Many relationships as it would complicate the http requests query params  even more. I will find a solution for that.
